### ISSUE TITLE
Blink Login Failure

### ISSUE THREAD

**Issue by WhooKnew** [colinbendell/homebridge-blink-for-home#49]
[20/02/2021, 08:38:29] [Blink] TypeError: this.enqueueConfigurationUpdate is not a function
    at PlatformAccessory.Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:466:12)
    at BlinkNetwork.createAccessory (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:195:37)
    at /usr/local/lib/node_modules/homebridge-blink-for-home/src/index.js:54:60
    at Array.map (<anonymous>)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/index.js:54:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[20/02/2021, 08:38:29] [Blink] NOTE: Blink devices in HomeKit will not be responsive.

I get this failure.

Can andybody please help?

Thank you

**Comment by mowen87** [comment]
I’m getting the same. And earlier had a different error
![69B8F87C-E07F-4DAE-A339-0095EF2B5D8A](https://user-images.githubusercontent.com/79358804/108591974-5c27c980-7363-11eb-8f7d-08ec1ebaa9dd.jpeg)

**Comment by GuzzaPower** [comment]
Happening to me too with HB 1.3.0

**Comment by ratsoid** [comment]
I'm experiencing the same error as OP since upgrading Homebridge to 1.3.0

**Comment by juergen-venne** [comment]
Same here Homebridge 1.3.0

[20/02/2021, 12:34:37] [Blink] Initing: Blink:Network:3098
[20/02/2021, 12:34:38] [Blink] TypeError: this.enqueueConfigurationUpdate is not a function
    at PlatformAccessory.Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:466:12)
    at BlinkNetwork.createAccessory (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:195:37)
    at /usr/local/lib/node_modules/homebridge-blink-for-home/src/index.js:54:60
    at Array.map (<anonymous>)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/index.js:54:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by rcoletti116** [comment]
Same as #44. @colinbendell made a fix but hasn’t published a release yet.

**Comment by colinbendell** [comment]
Just completing last set of testing. Help is welcome.

**Comment by WhooKnew** [comment]
@colinbendell - if you tell me how I would love to help or test :-)

BR

**Comment by xImportExportx** [comment]
i'm also seeing this with homebridge 1.3.0

[2/19/2021, 9:54:46 PM] [Blink] Initing: Blink:Network:151084
[2/19/2021, 9:54:46 PM] [Blink] TypeError: this.enqueueConfigurationUpdate is not a function
    at PlatformAccessory.Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:466:12)
    at BlinkNetwork.createAccessory (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:195:37)
    at /homebridge/node_modules/homebridge-blink-for-home/src/index.js:54:60
    at Array.map (<anonymous>)
    at HomebridgeBlink.init (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:54:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2/19/2021, 9:54:46 PM] [Blink] NOTE: Blink devices in HomeKit will not be responsive.

**Comment by ratsoid** [comment]
Everything is now fixed on my end - Pi3, Homebridge Image 1.3.0, Blink XT & XT2. Also prior bugs seem to now be fixed as well!

Thank you @colinbendell !

**Comment by colinbendell** [comment]
thanks! great to hear!

@WhooKnew the only way I know how testing can be done is having a local git clone. I'm digging in a bit to a) build better mock/tests and b) see if there is a better way to deliver pre-release versions into homebridge to make it easier for community testing. stay tuned!

**Comment by mowen87** [comment]
Thanks @colinbendell
